# Example YAML configuration with fake secrets for testing NoLeak scanner
# WARNING: These are fake secrets for testing purposes only!

app:
  name: "MyApplication"
  version: "1.2.3"
  debug: true

database:
  host: "localhost"
  port: 5432
  name: "myapp_production"
  user: "admin"
  password: "database_super_secret_password_123"
  connection_string: "postgres://dbuser:dbpassword@db.example.com:5432/production"
  ssl_mode: "require"

redis:
  host: "localhost"
  port: 6379
  password: "redis_secret_password_456"
  url: "redis://:redis_auth_password@redis.example.com:6379/0"

api_keys:
  stripe:
    secret: "sk_live_abcdefghijklmnopqrstuvwxyz123456"
    publishable: "pk_live_1234567890abcdef1234567890abcdef"
  
  google:
    api_key: "AIzaSyDaGmWKa4JsXZ-HjGw7ISLn_3namBGewQe"
    client_secret: "google_oauth_client_secret_abcdefghijklmnop"
  
  github:
    token: "ghp_github_personal_access_token_abcdefghijklmnopqr"
    webhook_secret: "github_webhook_secret_1234567890abcdef"
  
  slack:
    bot_token: "xoxb-123456789012-123456789012-abcdefghijklmnopqrstuvwx"
    webhook_url: "https://hooks.slack.com/services/T12345678/B12345678/secret123"

aws:
  access_key_id: "AKIAIOSFODNN7EXAMPLE"
  secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  session_token: "FwoGZXIvYXdzEBEaDHU0bXU3b1BQNjBWdyK2AaGVhWh5pYpNyQ=="
  region: "us-east-1"
  s3:
    bucket: "my-secret-bucket"
    access_key: "s3_specific_access_key_abcdefghijklmnop"

email:
  smtp:
    host: "smtp.gmail.com"
    port: 587
    username: "noreply@example.com"
    password: "smtp_authentication_password_secret"
    use_tls: true
  
  sendgrid:
    api_key: "SG.sendgrid_api_key_abcdefghijklmnopqrstuvwxyz.123456"

jwt:
  secret: "jwt_signing_secret_key_for_tokens_123456789"
  algorithm: "HS256"
  expiration: 3600

oauth:
  providers:
    google:
      client_id: "1234567890.apps.googleusercontent.com"
      client_secret: "google_oauth_secret_abcdefghijklmnopqrstuvwx"
    
    facebook:
      app_id: "1234567890123456"
      app_secret: "facebook_app_secret_abcdefghijklmnopqrstuvwxyz"

monitoring:
  sentry:
    dsn: "https://sentry_key_123@sentry.io/project_id"
  
  datadog:
    api_key: "datadog_api_key_abcdefghijklmnopqrstuvwxyz123456"

payment:
  paypal:
    client_id: "paypal_client_id_abcdefghijklmnopqrstuvwx"
    client_secret: "paypal_client_secret_1234567890abcdefghijklmn"
  
  square:
    application_id: "square_app_id_abcdefghijklmnopqrstuvwx"
    access_token: "square_access_token_1234567890abcdefghijklmnop"

sms:
  twilio:
    account_sid: "ACabcdefghijklmnopqrstuvwxyz123456"
    auth_token: "twilio_auth_token_abcdefghijklmnopqrstuvwx"
    phone_number: "+1234567890"

storage:
  s3:
    access_key: "AKIA123456789EXAMPLE"
    secret_key: "s3_secret_key_abcdefghijklmnopqrstuvwxyz123456"
    bucket: "app-data-bucket"
  
  azure:
    connection_string: "DefaultEndpointsProtocol=https;AccountName=myaccount;AccountKey=azure_key_123;EndpointSuffix=core.windows.net"

# Certificates and keys
ssl:
  private_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5/example
    -----END PRIVATE KEY-----
  
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDXTCCAkWgAwIBAgIJAExample...
    -----END CERTIFICATE-----

# Database connections as full URLs
connections:
  postgresql: "postgres://user:password@localhost:5432/dbname"
  mysql: "mysql://admin:secret123@db.example.com:3306/production"
  mongodb: "mongodb://dbuser:dbpass@cluster.mongodb.net/myapp"
  redis: "redis://:password@redis.example.com:6379/0"

# Docker registry credentials
docker:
  registry: "registry.example.com"
  username: "docker_user"
  password: "docker_registry_password_secret_123"
  auth_token: "dckr_pat_1234567890abcdef1234567890abcdef"

# Development secrets (still should be detected)
development:
  api_key: "dev_api_key_1234567890abcdef"
  database_password: "dev_db_password_not_secure"
  
# Comments with secrets (should still be detected)
# TODO: Replace with actual production key: prod_key_abcdefghijklmnop
# Old password was: old_password_123_change_me 